### PR TITLE
Added June 17 CUs for SharePoint 2016, 2013 and Project Server 2013

### PR DESCRIPTION
**Pull request by cvollmann**

### CODE REVIEW

**Comment by spjeff** [comment]
Thanks!  Merged PR.

**Comment by cvollmann** [comment]
Are you sure that it's merged? Looks like the CSV is still the old one.

**Comment by spjeff** [comment]
I manually copy/pasted the new lines and updated. 

Not sure why Github auto Merge didn't do that, but looks good now.  Really appreciate your help!

https://github.com/spjeff/sppatchify/blob/master/SPPatchify-Download-CU.csv

**Comment by rolandoldengarm** [comment]
Something is not right @spjeff , when running the script it doesn't display June:

image

**Comment by spjeff** [comment]
Try downloading the latest release ZIP please.

I ran a local test of "SPPatchify.ps1 -d" for download mode on Windows 10 desktop and it looks good.

image

image

**Pull request closed without merging**
